# Cross compilation configuration for Orkee

[build]
# Use vendored OpenSSL for all targets
env.OPENSSL_STATIC = "1"
env.OPENSSL_FEATURES = "vendored"

[target.x86_64-unknown-linux-gnu]
# Use the default cross image which includes build essentials

[target.aarch64-unknown-linux-gnu]
# Use the default cross image which includes build essentials

[target.x86_64-pc-windows-msvc]
# Windows target needs wine for testing (optional)
runner = "wine"