[package]
name = "openspec"
version.workspace = true
edition.workspace = true
description = "OpenSpec specification system for spec-driven development"
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Core package
orkee_core = { path = "../core" }

# Database
sqlx = { version = "0.8.1", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "uuid", "chrono", "migrate", "macros", "json"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Date/Time
chrono = { version = "0.4", features = ["serde"] }

# Async runtime
tokio = { version = "1.0", features = ["fs", "macros", "rt"] }

# Utilities
regex = "1.10"
sha2 = "0.10"

# Error handling
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.0"
tokio-test = "0.4"
