[package]
name = "orkee-tui"
version = "0.0.1"
edition = "2021"
description = "Terminal user interface for Orkee"


[dependencies]
ratatui = "0.28"
crossterm = "0.27"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
orkee-projects = { path = "../projects" }
chrono = "0.4"
anyhow = "1.0"