[package]
name = "orkee-tui"
version = "0.0.1"
edition = "2021"
description = "Terminal user interface for Orkee"
authors = ["Orkee Team"]
license = "MIT"
repository = "https://github.com/OrkeeAI/orkee"


[dependencies]
ratatui = "0.28"
crossterm = "0.27"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
orkee-projects = { path = "../projects" }
chrono = "0.4"
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4"] }
unicode-segmentation = "1.10"
unicode-width = "0.1"
strum = "0.25"
strum_macros = "0.25"
fuzzy-matcher = "0.3"
tui-input = "0.9"
tui-textarea = "0.6"