[package]
name = "orkee-preview"
version.workspace = true
edition.workspace = true
description = "Development server preview system for Orkee projects"
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "orkee_preview"
path = "src/lib.rs"


[dependencies]
# Configuration
orkee-config = { path = "../config" }

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# HTTP server and client
axum = { version = "0.7", features = ["macros", "tower-log", "multipart"] }
hyper = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.5", features = ["fs", "cors", "trace"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# File system and path handling
walkdir = "2.4"

# Process management
nix = { version = "0.27", features = ["process", "signal"] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
tracing = "0.1"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# UUID generation
uuid = { version = "1.0", features = ["v4", "serde"] }

# Regular expressions for log parsing
regex = "1.0"

# HTTP status codes
http = "1.0"

# Utilities
dirs = "5.0"
once_cell = "1.19"
sysinfo = "0.30"
futures = "0.3"
dotenvy = "0.15"

# Windows-specific dependencies
[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile = "3.8"
orkee-projects = { path = "../projects" }
serial_test = "3.2"