# Cargo Audit Configuration
# This file configures security auditing behavior for the Orkee project

[database]
# Use a specific advisory database URL for reliability
url = "https://github.com/RustSec/advisory-db.git"

# Allow using a slightly stale database to avoid network issues in CI
stale = false

[advisories]
# Currently no vulnerabilities to ignore, but this section exists for future use
ignore = [
    # Example: "RUSTSEC-2021-0001" - would ignore this specific advisory
]

# Categories of advisories to treat as warnings vs errors
informational_warnings = [
    "unmaintained",  # Warn about unmaintained packages
    "unsound",      # Warn about unsound packages  
    "notice"        # General notices
]

[output]
# Output format for reports
format = "terminal"

# Show additional context in reports
show-stats = true

[yanked]
# Whether to ignore yanked crates (packages removed from crates.io)
ignore = false