[package]
name = "orkee-projects"
version = "0.0.1"
edition = "2021"
description = "Project management library for Orkee"
authors = ["Orkee Team"]
license = "MIT"
repository = "https://github.com/OrkeeAI/orkee"

[dependencies]
# Database
sqlx = { version = "0.8.1", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "uuid", "chrono", "migrate", "macros"] }

# Async
async-trait = "0.1"

# Existing dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
rand = "0.8"
hex = "0.4"
axum = "0.7"
tower = { version = "0.4", features = ["util"] }
tracing = "0.1"
thiserror = "2.0"
tokio = { version = "1.0", features = ["fs"] }
git2 = "0.18"

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"

# Compression
flate2 = "1.0"

# Cloud Storage
aws-config = "1.5"
aws-sdk-s3 = "1.53"

# Security & Encryption
ring = "0.17"
argon2 = "0.5"
keyring = "3.6"

# Network & Utilities
backoff = { version = "0.4", features = ["tokio"] }
bytes = "1.5"
mime = "0.3"
toml = "0.8"

[dev-dependencies]
tempfile = "3.0"
tokio-test = "0.4"
mockall = "0.13"  # For trait mocking
wiremock = "0.6"  # For HTTP mocking