[package]
name = "orkee-projects"
version.workspace = true
edition.workspace = true
description = "Project management library for Orkee"
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Database
sqlx = { version = "0.8.1", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "uuid", "chrono", "migrate", "macros", "json"] }

# Async
async-trait = "0.1"

# Existing dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
rand = "0.8"
hex = "0.4"
axum = "0.7"
tower = { version = "0.4", features = ["util"] }
tracing = "0.1"
thiserror = "2.0"
tokio = { version = "1.0", features = ["fs"] }
git2 = "0.18"

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"

# Encryption
ring = "0.17"
base64 = "0.22"
machine-uid = "0.5"
argon2 = "0.5"

# Compression
flate2 = "1.0"

# Cloud functionality (optional)
orkee-cloud = { path = "../cloud", optional = true }

# Network & Utilities
mime = "0.3"
nanoid = "0.4.0"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
url = "2.5"

[features]
default = ["cloud"]
cloud = ["orkee-cloud"]

[dev-dependencies]
tempfile = "3.0"
tokio-test = "0.4"
mockall = "0.13"  # For trait mocking
wiremock = "0.6"  # For HTTP mocking
