[package]
name = "orkee-cloud"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Cloud sync functionality for Orkee AI agent orchestration platform"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# Core dependencies
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# HTTP Client
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# Authentication
open = "5.0"  # For opening browser

# Configuration
toml = "0.8"
dirs = "5.0"

# Security & Encryption (keep for future use)
ring = "0.17"
argon2 = "0.5"

# Utilities
hostname = "0.4"
hex = "0.4"

# Compression (for future snapshot functionality)
flate2 = "1.0"

# No dependency on projects to avoid circular dependency
# Cloud package is self-contained

[dev-dependencies]
tempfile = "3.0"
mockall = "0.13"
tokio-test = "0.4"
wiremock = "0.6"

[features]
default = []
# Enable integration tests
integration-tests = []