[package]
name = "orkee-config"
version.workspace = true
edition.workspace = true
description = "Configuration and environment variable management for Orkee"
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tracing = "0.1"
