[package]
name = "orkee-mcp-server"
version = "0.0.1"
edition = "2021"
description = "MCP server for Orkee project management"
authors = ["Orkee Team"]
license = "MIT"
repository = "https://github.com/yourusername/orkee"

[[bin]]
name = "orkee-mcp"
path = "src/main.rs"

[dependencies]
orkee-projects = { path = "../projects" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
signal-hook = "0.3"