[package]
name = "orkee-mcp-server"
version = "0.0.1"
edition = "2021"
description = "MCP server for Orkee project management"
authors = ["Orkee Team"]
license = "MIT"
repository = "https://github.com/yourusername/orkee"

[[bin]]
name = "orkee-mcp"
path = "src/main.rs"

[dependencies]
orkee-projects = { path = "../projects" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
signal-hook = "0.3"

[dev-dependencies]
rstest = "0.18"
mockall = "0.12"
wiremock = "0.6"
proptest = "1.4"
test-case = "3.1"
pretty_assertions = "1.4"
tempfile = "3.8"
tokio-test = "0.4"
futures = "0.3"