name: Publish to npm

on:
  workflow_run:
    workflows: ["Build Multi-Platform Binaries"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: "1.2.23"

      - name: Sync version from Cargo.toml to package.json
        working-directory: packages/cli
        run: |
          echo "Syncing version from Cargo.toml to package.json..."
          node scripts/sync-version.js

          # Show the synced version
          VERSION=$(node -p "require('./package.json').version")
          echo "Publishing version: $VERSION"

      - name: Install dependencies
        working-directory: packages/cli
        run: bun install
      
      - name: Publish to npm
        working-directory: packages/cli
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}